Inventory payload requests to use namespace
konveyor/virt-ui pull request #209
Opened 2020-11-12 11:06 UTC by gildub

The API call to the inventory-payload app is going to change slightly to go from:
`/api/v1/extract?providers=provider1,provider2`
to:
`/api/v1/extract?providers=namespace1/provider1,namespace2/provider2`

Will move from draft PR once it's available upstream in konveyor/virt-payload.

2020-11-13 21:45 UTC, gildub commented
@mturley, @konveyor/virt-payload has been updated, could you please review?

2020-11-16 10:18 UTC, gildub commented
Updated after http proxy addition.

2020-11-16 14:22 UTC, mturley requested changes
Sorry @gildub , I started a review and wrote this comment on Friday and then forgot to submit it. Once this change is made I'll approve and merge!

2020-11-16 15:01 UTC, mturley approved these changes

2020-11-16 15:01 UTC, gildub commented on src/app/Providers/components/ProvidersTable/VMware/VMwareProvidersTable.tsx
> +    .map((provider) => `${VIRT_META.namespace}/${provider.name}`)
You're right. Thanks. Fixed.

2020-11-16 15:06 UTC, merged